*** Settings ***
Resource        pages/LoginPage.robot
Resource        pages/HomePage.robot
Resource        pages/Navbar.robot
Resource        pages/ProfilePage.robot
Resource        steps/CommonStep.robot
Resource        steps/LoginStep.robot
Resource        steps/HomeStep.robot
Resource        steps/NavbarStep.robot
Resource        steps/ProfileStep.robot
Resource        Common.robot
Resource        api/Api.robot