*** Settings ***
Resource        pages/loginPage.robot
Resource        pages/mainPage.robot
Resource        pages/navbar.robot
Resource        pages/profilePage.robot
Resource        steps/commonStep.robot
Resource        steps/loginStep.robot
Resource        steps/mainStep.robot
Resource        steps/navbarStep.robot
Resource        steps/profileStep.robot
Resource        common.robot
Resource        api/api.robot